### ISSUE TITLE
First song fails, skip, go back, works.

### ISSUE THREAD

**Issue by roninniagara** [Rodmg/linamp#9]
Easy to replicate. If i create a playlist of an album, then go to the player - hit play. no go.

Skip to song 2, plays. Go back to song 1 by hitting back, plays.

Happens almost every time.

I'm using this a LOT! :)

**Comment by Rodmg** [comment]
Thanks for reporting, I've seen this issue too, but haven't located the source of the issue.

This is how I'm able to replicate it:

When the player is first started, when I select any song or list of songs and add it to the playlist, the player gets to the "Play" state trying to play the first item I added, but it doesn't start playing.

(By design, when you add something to the playlist and is not playing it will start playing it)

If I click the stop button and then play, it works.

My first guess is that we are falling into a race condition somewhere, where the player tries to start playing, but something is not ready, either the buffer, or something on the underlying library (Gstreamer), or the audio pipeline.

**Comment by roninniagara** [comment]
yep. same. not a huge deal. 

I'm really enjoying this a lot. I use it way more than I thought i would :D
